### Get a new note
POST http://localhost:3000/note/newnote
Content-Type: application/json

{
    "title": "Hello",
    "content": "This is a new note"
}

### Get all notes

GET  http://localhost:3000/note


### Get note by ID

GET  http://localhost:3000/note/2130611f-1cd6-4a62-b10b-afec17eff8ac

### UPDATE NOTE

PUT  http://localhost:3000/note/update/2130611f-1cd6-4a62-b10b-afec17eff8ac
Content-Type: application/json

{
    "title": "Hello",
    "content": "This is an updated note"
}

### Delete Note

DELETE   http://localhost:3000/note/delete/2130611f-1cd6-4a62-b10b-afec17eff8ac